# Gradle properties
org.gradle.jvmargs=-Xmx6G

# Mod Properties
mod.archives_base_name=TweakMyClient
mod.artifact_name=tweak_my_client
mod.description=Add something interesting <3
mod.homepage=https://github.com/Hendrix-Shen/Tweak-My-Client
mod.id=tweak_my_client
mod.license=LGPL-3
mod.license_url=https://www.gnu.org/licenses/lgpl-3.0.txt
mod.maven_group=top.hendrixshen.tweak-my-client
mod.name=Tweak My Client
mod.sources=https://github.com/Hendrix-Shen/Tweak-My-Client
mod.version=4.0

# Development Environment
## MagicLib
dependencies.magiclib_dependency=0.8.801
