# Dependency Versions
dependencies.minecraft_dependency=1.14.x
dependencies.minecraft_version=1.14.4

# Litematica - 0.0.0-dev.20200123.linearpaste
dependencies.api.litematica_version=0.0.0-dev.20200123.linearpaste

# Publish properties
publish.game_version=1.14.4
publish.dependencies_list=\
  magiclib(required){modrinth:mv1zH6ln}{curseforge:576459}#(ignore:github),\
  malilib(required){modrinth:GcWjdA9I}{curseforge:303119}#(ignore:github)
