name: Question
description: Anything you don't understand
title: "[Question] "
labels:
  - "type: question"
  - "resolution: unresolved"
  - "status: awaiting"
body:
  - type: dropdown
    id: question-type
    attributes:
      label: Question Type
      options:
        - "Codes"
        - "Usages"
        - "Others"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please tell us the question is with a clear and detailed description, put your screenshots if possible.
    validations:
      required: true
