# Dependency Versions
dependencies.minecraft_dependency=1.19.4
dependencies.minecraft_version=1.19.4

# Litematica - 0.14.7
dependencies.api.litematica_version=0.14.7
# Not Enough Crashes - 4.1.4
# notenoughcrashes-4.1.4+1.16.5-fabric.jar
dependencies.api.not_enough_crashes_version=4.1.4+1.16.5-fabric

# Publish properties
publish.game_version=1.19.4
publish.dependencies_list=\
  carpet(optional){modrinth:TQTTVgYE}{curseforge:349239}#(ignore:github),\
  malilib(optional){modrinth:GcWjdA9I}{curseforge:303119}#(ignore:github)
