# Dependency Versions
dependencies.forge_version=47.4.10
dependencies.minecraft_dependency=1.20.1
dependencies.minecraft_version=1.20.1

# Litematica - 0.1.13
dependencies.api.litematica_version=0.1.13-mc1.20.1

# Loom Properties
loom.platform=forge

# Publish properties
publish.game_version=1.20.1
publish.dependencies_list=\
  magiclib(required){modrinth:mv1zH6ln}{curseforge:576459}#(ignore:github),\
  mafglib(optional){modrinth:SKI34J7B}{curseforge:910766}#(ignore:github)
